os:
  - linux
#  - osx       ## no travis support
#  - windows   ## no travis support 
language: python
python:
  - "3.7"
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
script:
  - pytest --cov=penopype
after_success:
  - coveralls
