image:
# - Ubuntu1804
- Visual Studio 2019
# - macOS

branches:
  only:
    - development

environment:
  matrix:
  - TOXENV: py37
    PYTHON: "C:\\Python37-x64"
  
# ~/venv3.7.5

build:
  off

install:
- "SET PATH=%PYTHON%; %PYTHON%\\Scripts; %PATH%"
- pip install -U pip
- pip install tox"

test_script:
- tox

