image:
- Ubuntu1804
- Visual Studio 2019
- macOS

branches:
  only:
    - development

environment:
  PY_DIR: C:\Python37-x64

build:
  off

install:
- pip install pytest
- pip install pytest-cov
- pip install coveralls
- pip install .
  
test_script:
- pytest --cov=penopype

after_test:
coveralls
